// Vehicle state model, telemetry Flows, command protocol (ACK/retry), mission upload/download state machine,
// and the KFT login (spec S12).
import java.util.Properties
import org.jetbrains.kotlin.gradle.plugin.KotlinPlatformType

plugins { id("kft.kmp.library") }

// ---- KFT login key (spec S12, ADR-003) ----
// Same sources as the Esri key (app/desktop/build.gradle.kts): `KFT_APP_SECRET=` in local.properties (git-ignored),
// else the KFT_APP_SECRET environment variable. Unlike the Esri key it can't be handed over at `run` time, because
// the Android APK and the packaged desktop app need it too, so it is compiled into a generated Kotlin file under
// build/ (never committed). No key, or not 64 hex characters: the file holds "", the build still succeeds (CI),
// and the app shows "KFT login: no key configured" instead of trying to log in.
val kftAppSecret: Provider<String> = providers.fileContents(rootProject.layout.projectDirectory.file("local.properties")).asText
    .map { text -> Properties().apply { load(text.reader()) }.getProperty("KFT_APP_SECRET").orEmpty() }
    .orElse("")
    .zip(providers.environmentVariable("KFT_APP_SECRET").orElse("")) { fromFile, fromEnv -> fromFile.ifBlank { fromEnv }.trim() }

/** Writes `KftAppSecret.kt`. The value is validated here only so nothing but hex can ever land in Kotlin source. */
abstract class GenerateKftAppSecret : DefaultTask() {
    @get:Input abstract val secret: Property<String>
    @get:OutputDirectory abstract val outputDir: DirectoryProperty

    @TaskAction
    fun generate() {
        val hex = secret.get().takeIf { Regex("[0-9a-fA-F]{64}").matches(it) }.orEmpty()
        val file = outputDir.file("com/kft/gcs/core/vehicle/KftAppSecret.kt").get().asFile
        file.parentFile.mkdirs()
        file.writeText(
            """
            |package com.kft.gcs.core.vehicle
            |
            |// GENERATED by :core:vehicle:generateKftAppSecret from KFT_APP_SECRET. Lives in build/, never commit it.
            |// Empty = no valid key configured.
            |internal const val KFT_APP_SECRET_HEX: String = "$hex"
            |""".trimMargin(),
        )
    }
}

val generateKftAppSecret = tasks.register<GenerateKftAppSecret>("generateKftAppSecret") {
    secret.set(kftAppSecret)
    outputDir.set(layout.buildDirectory.dir("generated/kftAppSecret/commonMain/kotlin"))
}

kotlin {
    // javax.crypto exists on Android and desktop alike, so the HMAC is written once in "jvmCommon" (as core:mavlink
    // does for sockets). See ADR-003 for why not a multiplatform crypto library.
    @OptIn(org.jetbrains.kotlin.gradle.ExperimentalKotlinGradlePluginApi::class)
    applyDefaultHierarchyTemplate {
        common {
            group("jvmCommon") {
                withJvm()
                withCompilations { it.target.platformType == KotlinPlatformType.androidJvm }
            }
        }
    }

    sourceSets {
        commonMain {
            // flatMap to the task's @OutputDirectory: Gradle then knows to run the generator before compiling.
            kotlin.srcDir(generateKftAppSecret.flatMap { it.outputDir })
            dependencies {
                api(project(":core:mavlink"))
                api(project(":core:geo"))
                implementation(project.dependencies.platform(libs.koin.bom))
                implementation(libs.koin.core)
            }
        }
    }
}
